/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fb_screenshotapp_fbjni */

#ifndef _Included_com_fb_screenshotapp_fbjni
#define _Included_com_fb_screenshotapp_fbjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fb_screenshotapp_fbjni
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fb_screenshotapp_fbjni_test
  (JNIEnv *, jclass);

/*
 * Class:     com_fb_screenshotapp_fbjni
 * Method:    screenPngBytes
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fb_screenshotapp_fbjni_screenPngBytes
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fb_screenshotapp_fbjni
 * Method:    captureScreen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fb_screenshotapp_fbjni_bufferlength
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
